---
- hosts: ucs
  connection: local
  gather_facts: no

  tasks:
  - name: Login {{ucsm_ip}}
    ucs_login:
      ip={{ ucsm_ip }}
      username={{ ucsm_user }}
      password={{ ucsm_pass }}
    register: handle_output

  - name: Configure Dns Server {{ ucsm_ip }}
    admin_dns:
      name="8.8.8.8"
      state="present"
      handle={{ handle_output.handle }}

  - name: Create Boot Policy and Boot order 1 {{ ucsm_ip }}
    conf_mo_test:
      LsbootPolicy: 
        descr: "8.8.8.8" 
        name: "8.8.8.8"
        parent_mo_or_dn: "org-root"

  - name: Create Boot Policy and Boot order test  {{ ucsm_ip }}
    conf_mo_test:
      LsbootPolicy: 
        descr: "8.8.8.8" 
        name: "8.8.8.8"
        parent_mo_or_dn: "org-root"
      LsbootBootSecurity: 
        secure_boot: "no"
      LsbootLan: 
        prot: "pxe" 
        order: "2"
      LsbootSan: 
        order: 1

  - name: Create Boot Policy and Boot order  {{ ucsm_ip }}
    conf_mo_test:
      LsbootPolicy: 
        descr: "8.8.8.8" 
        name: "8.8.8.8"
        parent_mo_or_dn: "org-root"
      LsbootBootSecurity: 
        secure_boot: "no"
      LsbootLan: 
        prot: "pxe" 
        order: "2"
        LsbootLanImagePath:
           vnic_name: "pxe"
      LsbootSan: 
        order: 1

  - name: Logout {{ ucsm_ip }}
    ucs_logout:
      handle={{ handle_output.handle }}

