---
- hosts: ucs
  connection: local
  gather_facts: no

  tasks:
  - name: Login {{ucsm_ip}}
    ucs_login:
      ip={{ ucsm_ip }}
      username={{ ucsm_user }}
      password={{ ucsm_pass }}
    register: handle_output

  - name: Create Boot Policy {{ boot_policy_name }}
    boot_policy:
      name={{ boot_policy_name }}
      descr={{ boot_policy_descr }}
      state="present"
      reboot_on_update="no"
      policy_owner="local"
      enforce_vnic_name={{ boot_policy_enforce_vnic_name }}
      boot_mode="legacy"
      handle={{ handle_output.handle }}

  - name: Add LAN Boot to {{ boot_policy_name }}
    boot_lan:
      name={{ boot_policy_name }}
      state="present"
      prot="pxe"
      order={{ lan_boot_order }}
      handle={{ handle_output.handle }}

  - name: Add LAN Boot vNIC {{ lan_boot_vnic_name }}
    boot_lan_vnic:
      name={{ boot_policy_name }}
      vnic_name={{ lan_boot_vnic_name }}
      state="present"
      handle={{ handle_output.handle }}

  - name: Logout {{ ucsm_ip }}
    ucs_logout:
      handle={{ handle_output.handle }}

