---
- hosts: ucs
  connection: local
  gather_facts: no

  tasks:
  - name: Login {{ucsm_ip}}
    ucs_login:
      ip={{ ucsm_ip }}
      username={{ ucsm_user }}
      password={{ ucsm_pass }}
    register: handle_output

  - name: Check desired configuration for Boot policy creation {{ ucsm_ip }}
    new_boot_module:
      name="sample4"
      descr="sample3"
      state="present"
      reboot_on_update="yes"
      policy_owner="local"
      enforce_vnic_name="yes"
      boot_mode="uefi"
      handle={{ handle_output.handle }}
    register: mo_bootpolicy

  - name: Check desired configuration for Boot Security creation {{ ucsm_ip }}
    new_boot_security:
      name="sample3"
      secure_boot="no"
      handle={{ handle_output.handle }}

  - name: Check desired configuration for Boot Lan creation {{ ucsm_ip }}
    new_boot_lan2:
      name="sample3"
      state="present"
      prot="pxe"
      order="5"
      mo_bootpolicy={{ mo_bootpolicy.mo_bootpolicy }}
      handle={{ handle_output.handle }}
    register: mo_bootlan

  - name: Check desired configuration for Boot Lan ImagePath {{ ucsm_ip }}
    new_boot_lan_image:
      name="testdemo13"
      vnic_name="test2"
      state="present"
      mo_bootlan={{ mo_bootlan.mo_bootlan }}
      handle={{ handle_output.handle }}

  - name: Logout {{ ucsm_ip }}
    ucs_logout:
      handle={{ handle_output.handle }}

