---
- hosts: ucs
  connection: local
  gather_facts: no

  tasks:
  - name: Login {{ucsm_ip}}
    ucs_login:
      ip={{ ucsm_ip }}
      username={{ ucsm_user }}
      password={{ ucsm_pass }}
    register: handle_output

  - name: Check desired configuration for Boot policy creation {{ ucsm_ip }}
    new_boot_module:
      name="sample3"
      descr="sample3"
      state="present"
      reboot_on_update="yes"
      policy_owner="local"
      enforce_vnic_name="yes"
      boot_mode="uefi"
      handle={{ handle_output.handle }}

  - name: Check desired configuration for Boot Security creation {{ ucsm_ip }}
    new_boot_security:
      name="sample3"
      secure_boot="no"
      handle={{ handle_output.handle }}

  - name: Check desired configuration for Boot Lan creation {{ ucsm_ip }}
    new_boot_lan:
      prot="pxe"
      order=1
      handle={{ handle_output.handle }}
    register: mo2_output

  - name: Logout {{ ucsm_ip }}
    ucs_logout:
      handle={{ handle_output.handle }}

