---
- hosts: ucs
  connection: local
  gather_facts: no

  tasks:
  - name: Login {{ucsm_ip}}
    ucs_login:
      ip={{ ucsm_ip }}
      username={{ ucsm_user }}
      password={{ ucsm_pass }}
    register: handle_output

  - name: Check desired configuration for Boot policy creation {{ ucsm_ip }}
    boot_policy:
      name="sample33"
      descr="sample3"
      reboot_on_update="yes"
      policy_owner="local"
      enforce_vnic_name="yes"
      boot_mode="uefi"
      handle={{ handle_output.handle }}
    register: mo1_output

  - name: Check desired configuration for Boot Lan creation {{ ucsm_ip }}
    boot_lan:
      prot="pxe"
      order=1
      mo1={{ mo1_output.mo_1 }}
      handle={{ handle_output.handle }}
    register: mo2_output

  - name: Logout {{ ucsm_ip }}
    ucs_logout:
      handle={{ handle_output.handle }}

