---
- hosts: ucs
  connection: local
  gather_facts: no

  tasks:
  - name: Login {{ ucsm_ip }}
    ucs_login:
      ip={{ ucsm_ip }}
      username={{ ucsm_user }}
      password={{ ucsm_pass }}
    register: handle_output

  - name: Remove Dns Server {{ ucsm_ip }}
    admin_dns:
      name="8.8.8.8"
      state="absent"
      handle={{ handle_output.handle }}

  - name: Remove Qos Policy {{ ucsm_ip }}
    network_qos_class:
      priority="platinum"
      cos="6"
      drop="drop"
      weight="best-effort"
      mtu="fc"
      multicast_optimize="yes"
      state="absent"
      handle={{ handle_output.handle }}

  - name: Logout {{ ucsm_ip }}
    ucs_logout:
      handle={{ handle_output.handle }}

