---
- hosts: ucs
  connection: local
  gather_facts: no

  tasks:
  - name: Login {{ ucsm_ip }}
    ucs_login:
      ip={{ ucsm_ip }}
      username={{ ucsm_user }}
      password={{ ucsm_pass }}
    register: handle_output

  - name: Configure Dns Server {{ ucsm_ip }}
    admin_dns:
      name="8.8.8.8"
      state="present"
      handle={{ handle_output.handle }}

  - name: Logout {{ ucsm_ip }}
    ucs_logout:
      handle={{ handle_output.handle }}

